name:                cardano-addresses-jsbits
version:             3.6.0
github:              input-output-hk/cardano-addresses
license:             Apache-2.0
author:              IOHK
maintainer:          operations@iohk.io
copyright:           2021 IOHK
synopsis:            Javascript code for ghcjs build of cardano-addresses.
category:            Cardano

description: |
  This package supports ghcjs compilation of cardano-addresses with
  Javascript wrappers and Emscripten builds of the cryptonite C
  sources.

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: lib
  default-extensions:
  - NoImplicitPrelude
  when:
  - condition: 'impl(ghcjs) || os(ghcjs)'
    # This file is not included in the git repo and should be built
    # manually, e.g. by running ./emscripten/build.sh, or via the nix build.
    ghc-options: jsbits/cardano-crypto.js
    js-sources: jsbits/cardano-crypto.js
  - condition: false
    other-modules: Paths_cardano_addresses_jsbits
